'use strict';

// Composes the scheduling reply that a goal connection implies, so approving it
// is the only step left.
//
// The body is built from a fixed template, never generated by a model. An
// inbound email is untrusted input, and a model asked to "reply to this" is a
// prompt-injection surface pointed directly at the owner's outbox — the owner
// would be approving text that the sender partly authored. Everything here is
// therefore assembled from trusted values (the owner's own calendar windows and
// configured name) with the two untrusted fields, the sender's display name and
// subject line, aggressively sanitized before use.
//
// The owner's goal text is deliberately never included: "setup partnership with
// identity iq" is a private note, not something to leak to the counterparty.

const { emailAddresses, displayName, isPublicMailboxDomain } = require('./entity_extraction');
const { describeOpenWindows } = require('./calendar_availability');

const MAX_SUBJECT = 160;
const MAX_GREETING_NAME = 40;

// Addresses that must never receive an automated reply.
const UNREPLYABLE_PATTERN = /(?:^|[._-])(?:no-?reply|do-?not-?reply|donotreply|mailer-daemon|postmaster|bounce|notifications?|automated)(?:$|[._@-])/i;

// Strips anything that could break out of a header or read as markup. Newlines
// in particular would be header injection in an outbound message.
function sanitizeHeaderText(value, limit) {
  return String(value || '')
    .replace(/[\r\n\t]+/g, ' ')
    .replace(/[<>]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, limit);
}

// A greeting is the one place untrusted text lands in the body, so it is
// reduced to a single plausible first name or dropped entirely. The whitelist
// below is the real gate, so apostrophes survive for names like O'Brien —
// in a plain-text body they cannot inject anything.
function sanitizeGreetingName(value) {
  const cleaned = String(value || '')
    .replace(/[\r\n]+/g, ' ')
    .replace(/["<>@]/g, '')
    .trim();
  const first = cleaned.split(/[\s,]+/).find(Boolean) || '';
  if (!/^[A-Za-z][A-Za-z'’-]{0,38}$/.test(first)) return '';
  return first.slice(0, MAX_GREETING_NAME);
}

function replySubject(subject) {
  const cleaned = sanitizeHeaderText(subject, MAX_SUBJECT);
  if (!cleaned) return 'Finding time to connect';
  return /^re:/i.test(cleaned) ? cleaned : `Re: ${cleaned}`;
}

function recipientAddress(signal = {}) {
  const [address] = emailAddresses(signal.from || signal.address || '');
  if (!address) return '';
  const local = address.split('@')[0] || '';
  if (UNREPLYABLE_PATTERN.test(local) || UNREPLYABLE_PATTERN.test(address)) return '';
  return address;
}

// Returns the staged reply, or null when replying would be wrong: no free time
// to offer, no repliable address, or the owner's own mailbox.
function buildSchedulingReply({
  signal = {},
  windows = [],
  ownerName = '',
  ownerEmail = ''
} = {}) {
  const availability = describeOpenWindows(windows);
  if (!availability) return null;

  const to = recipientAddress(signal);
  if (!to) return null;
  if (ownerEmail && to === String(ownerEmail).trim().toLowerCase()) return null;

  const greetingName = sanitizeGreetingName(displayName(signal.from) || signal.displayName || '');
  const greeting = greetingName ? `Hi ${greetingName},` : 'Hi,';
  const signOff = sanitizeGreetingName(ownerName) || sanitizeHeaderText(ownerName, MAX_GREETING_NAME);
  const offer = windows.length > 1
    ? `I have a few windows open — ${availability}. Would any of those work for you?`
    : `I'm open ${availability}. Would that work for you?`;

  const body = [
    greeting,
    '',
    'Thanks for reaching out — happy to find a time to talk.',
    '',
    offer,
    '',
    'Best,',
    signOff || 'Chris'
  ].join('\n');

  return {
    to,
    subject: replySubject(signal.subject),
    body,
    // Personal-domain senders are more likely to be individuals than a shared
    // company mailbox; surfaced so callers can log it, not to gate the draft.
    personal_domain: isPublicMailboxDomain(to.split('@')[1] || '')
  };
}

module.exports = {
  MAX_GREETING_NAME,
  MAX_SUBJECT,
  UNREPLYABLE_PATTERN,
  buildSchedulingReply,
  recipientAddress,
  replySubject,
  sanitizeGreetingName,
  sanitizeHeaderText
};
