-- AURA cloud-state schema
-- Run this once in the Supabase SQL Editor as the project owner.

create extension if not exists pgcrypto;

create table if not exists public.aura_conversations (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete cascade,
  title text not null default 'AURA Conversation',
  summary text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.aura_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid references public.aura_conversations(id) on delete cascade,
  owner_id uuid references auth.users(id) on delete cascade,
  role text not null check (role in ('system', 'user', 'assistant', 'tool')),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.aura_memories (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete cascade,
  content text not null,
  kind text not null default 'fact',
  source text not null default 'conversation',
  confidence double precision not null default 0.8 check (confidence between 0 and 1),
  sensitivity text not null default 'private',
  embedding jsonb,
  superseded_by uuid references public.aura_memories(id),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists aura_memories_owner_content_active
  on public.aura_memories(owner_id, lower(content))
  where superseded_by is null;

create table if not exists public.aura_notifications (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users(id) on delete cascade,
  text text not null,
  category text not null default 'general',
  urgency text not null default 'normal'
    check (urgency in ('low', 'normal', 'high', 'critical')),
  dedupe_key text,
  metadata jsonb not null default '{}'::jsonb,
  delivered_at timestamptz,
  acknowledged_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.aura_notifications
  add column if not exists dedupe_key text;

create table if not exists public.aura_state (
  owner_id uuid references auth.users(id) on delete cascade,
  key text not null,
  value jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (owner_id, key)
);

create table if not exists public.aura_agents (
  id text primary key,
  owner_id uuid references auth.users(id) on delete cascade,
  name text not null,
  description text not null,
  instructions text not null,
  allowed_tools jsonb not null default '[]'::jsonb,
  maximum_risk text not null default 'read'
    check (maximum_risk in ('read', 'reversible_write', 'external_action')),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.aura_tasks (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete cascade,
  parent_task_id uuid references public.aura_tasks(id) on delete set null,
  assigned_agent text references public.aura_agents(id) on delete set null,
  title text not null,
  description text,
  status text not null default 'pending'
    check (status in ('pending', 'planning', 'awaiting_approval', 'running', 'blocked', 'completed', 'failed', 'cancelled')),
  priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high', 'urgent')),
  due_at timestamptz,
  input jsonb not null default '{}'::jsonb,
  evidence jsonb not null default '[]'::jsonb,
  result jsonb,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.aura_actions (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete cascade,
  task_id uuid references public.aura_tasks(id) on delete cascade,
  agent_id text references public.aura_agents(id) on delete set null,
  tool_name text not null,
  arguments jsonb not null default '{}'::jsonb,
  risk_level text not null
    check (risk_level in ('read', 'reversible_write', 'external_action')),
  status text not null default 'proposed'
    check (status in ('proposed', 'approved', 'rejected', 'executing', 'succeeded', 'failed', 'cancelled')),
  requires_approval boolean not null default true,
  approved_by uuid references auth.users(id),
  approved_at timestamptz,
  result jsonb,
  error text,
  created_at timestamptz not null default now(),
  executed_at timestamptz
);

create table if not exists public.aura_companion_jobs (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete cascade,
  target_device text not null,
  capability text not null,
  request jsonb not null default '{}'::jsonb,
  status text not null default 'queued'
    check (status in ('queued', 'claimed', 'succeeded', 'failed', 'expired', 'cancelled')),
  claimed_at timestamptz,
  completed_at timestamptz,
  expires_at timestamptz not null default (now() + interval '15 minutes'),
  result jsonb,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists aura_messages_conversation_created
  on public.aura_messages(conversation_id, created_at);
create index if not exists aura_notifications_owner_unread
  on public.aura_notifications(owner_id, acknowledged_at, created_at desc);
create unique index if not exists aura_notifications_owner_dedupe
  on public.aura_notifications(owner_id, dedupe_key)
  where dedupe_key is not null;
create index if not exists aura_tasks_owner_status
  on public.aura_tasks(owner_id, status, created_at desc);
create index if not exists aura_actions_task_status
  on public.aura_actions(task_id, status, created_at);
create index if not exists aura_companion_jobs_device_status
  on public.aura_companion_jobs(target_device, status, created_at);

alter table public.aura_conversations enable row level security;
alter table public.aura_messages enable row level security;
alter table public.aura_memories enable row level security;
alter table public.aura_notifications enable row level security;
alter table public.aura_state enable row level security;
alter table public.aura_agents enable row level security;
alter table public.aura_tasks enable row level security;
alter table public.aura_actions enable row level security;
alter table public.aura_companion_jobs enable row level security;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'aura_conversations', 'aura_messages', 'aura_memories',
    'aura_notifications', 'aura_state', 'aura_agents', 'aura_tasks',
    'aura_actions', 'aura_companion_jobs'
  ]
  loop
    execute format('drop policy if exists "owner access" on public.%I', table_name);
    execute format(
      'create policy "owner access" on public.%I for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid())',
      table_name
    );
  end loop;
end $$;

insert into public.aura_agents
  (id, name, description, instructions, allowed_tools, maximum_risk)
values
  (
    'client_operations',
    'Client Operations Agent',
    'Audits client progress, phases, missing records, and stalled workflows.',
    'Use deterministic CCC tools. Report evidence and never modify client records.',
    '["get_client_snapshot","get_client_current_phase","query_database_table","count_database_rows"]'::jsonb,
    'read'
  ),
  (
    'finance',
    'Finance Agent',
    'Reconciles collections, recurring revenue, balances, and commissions.',
    'Use deterministic financial tools and state the accounting definition behind every metric.',
    '["calculate_financial_metrics","get_outstanding_balances","query_database_table","count_database_rows"]'::jsonb,
    'read'
  )
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  instructions = excluded.instructions,
  allowed_tools = excluded.allowed_tools,
  maximum_risk = excluded.maximum_risk,
  updated_at = now();
