-- Safe, approval-driven LinkedIn relationship assistance for an existing AURA install.
-- Run once in the Supabase SQL Editor after supabase_aura_brain.sql.

create table if not exists public.aura_linkedin_relationships (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete cascade,
  profile_url text not null,
  linkedin_member_urn text,
  conversation_urn text,
  display_name text not null,
  headline text,
  location text,
  profile_summary text,
  conversation_context text,
  last_interaction_at timestamptz,
  topic text,
  intended_next_step text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner_id, profile_url)
);

create table if not exists public.aura_linkedin_drafts (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete cascade,
  relationship_id uuid not null references public.aura_linkedin_relationships(id) on delete cascade,
  action_id uuid references public.aura_actions(id) on delete set null,
  supersedes_draft_id uuid references public.aura_linkedin_drafts(id) on delete set null,
  recipient_member_urn text,
  conversation_urn text,
  version integer not null check (version > 0),
  approval_code text not null,
  message_type text not null check (message_type in (
    'connection_request', 'introduction', 'follow_up', 'reply', 'thank_you',
    'collaboration', 'reconnect', 'move_to_call', 'other'
  )),
  purpose text not null,
  subject text,
  body text not null,
  status text not null default 'draft' check (status in (
    'draft', 'approved', 'rejected', 'sent', 'failed', 'superseded'
  )),
  approved_at timestamptz,
  sent_at timestamptz,
  delivery_receipt jsonb,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner_id, approval_code),
  unique (relationship_id, version),
  unique (action_id)
);

alter table public.aura_linkedin_drafts
  add column if not exists recipient_member_urn text;
alter table public.aura_linkedin_drafts
  add column if not exists conversation_urn text;
alter table public.aura_linkedin_drafts
  add column if not exists subject text;

create table if not exists public.aura_linkedin_audit (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users(id) on delete cascade,
  relationship_id uuid references public.aura_linkedin_relationships(id) on delete cascade,
  draft_id uuid references public.aura_linkedin_drafts(id) on delete set null,
  action_id uuid references public.aura_actions(id) on delete set null,
  event_type text not null check (event_type in (
    'context_saved', 'context_reviewed', 'draft_created', 'draft_edited',
    'draft_approved', 'draft_rejected', 'send_succeeded', 'send_failed'
  )),
  actor text not null check (actor in ('owner', 'aura', 'connector')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists aura_linkedin_relationships_owner_updated
  on public.aura_linkedin_relationships(owner_id, updated_at desc);
create index if not exists aura_linkedin_drafts_relationship_created
  on public.aura_linkedin_drafts(relationship_id, created_at desc);
create index if not exists aura_linkedin_drafts_owner_status
  on public.aura_linkedin_drafts(owner_id, status, created_at desc);
create index if not exists aura_linkedin_audit_relationship_created
  on public.aura_linkedin_audit(relationship_id, created_at desc);

alter table public.aura_linkedin_relationships enable row level security;
alter table public.aura_linkedin_drafts enable row level security;
alter table public.aura_linkedin_audit enable row level security;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'aura_linkedin_relationships', 'aura_linkedin_drafts'
  ]
  loop
    execute format('drop policy if exists "owner access" on public.%I', table_name);
    execute format(
      'create policy "owner access" on public.%I for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid())',
      table_name
    );
  end loop;
end $$;

drop policy if exists "owner access" on public.aura_linkedin_audit;
drop policy if exists "owner audit read" on public.aura_linkedin_audit;
drop policy if exists "owner audit insert" on public.aura_linkedin_audit;
create policy "owner audit read" on public.aura_linkedin_audit
  for select to authenticated using (owner_id = auth.uid());
create policy "owner audit insert" on public.aura_linkedin_audit
  for insert to authenticated with check (owner_id = auth.uid());

-- Once an approval action points at a draft, the exact recipient relationship,
-- purpose, type, and body are immutable. Revisions create a new version and a
-- new approval action instead of changing text the owner already reviewed.
create or replace function public.protect_linkedin_draft_content()
returns trigger
language plpgsql
as $$
begin
  if old.action_id is not null and (
    new.owner_id is distinct from old.owner_id or
    new.relationship_id is distinct from old.relationship_id or
    new.supersedes_draft_id is distinct from old.supersedes_draft_id or
    new.recipient_member_urn is distinct from old.recipient_member_urn or
    new.conversation_urn is distinct from old.conversation_urn or
    new.version is distinct from old.version or
    new.approval_code is distinct from old.approval_code or
    new.message_type is distinct from old.message_type or
    new.purpose is distinct from old.purpose or
    new.subject is distinct from old.subject or
    new.body is distinct from old.body or
    new.action_id is distinct from old.action_id
  ) then
    raise exception 'An approval-bound LinkedIn draft is immutable; create a new version.';
  end if;
  return new;
end;
$$;

drop trigger if exists protect_linkedin_draft_content on public.aura_linkedin_drafts;
create trigger protect_linkedin_draft_content
before update on public.aura_linkedin_drafts
for each row execute function public.protect_linkedin_draft_content();
